[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, X-Form-Secret"
  Access-Control-Allow-Methods = "POST, OPTIONS"